// all the challenges
var challenges = [
    "Create a website with a table.",
    "Create an animation using the canvas.",
    "Create an animation using svg.",
    "Create a blog.",
    "Create a website that gets info from user.",
    "Create a website with a graph.",
    "Create a progress bar.",
    "Create a music website.",
    "Create a image slide of one of your hobbies.",
    "Create an animation using keyframes.",
    "Create an animation no using canvas, keyframes, or svg",
    "Create a website with an pop up.",
    "Create a website an list",
    "Create an cool design for an website",
    "Copy something cool from another website.",
    "Create a user log in.",
    "Update an old project",
    "Make something and show it to people",
    "Create something with a lot of math.",
    "Create a small game.",
    "Create a website in the fewest lines of code you can.",
    "Create a game with the fewest line of code you can.",
    "Create a review website.",
    "Create a shopping website.",
    "Create a website that plays videos.",
    "Create a website that elements are ad or removed.",
    "Create a website that haves links.",
    "Create a website that has iframe in it.",
    "Make a website that works on all devices",
    "Create a website that has random numbers in it.",
    "Create a website that uses the date.",
    "Create a count down website.",
    "Create a website about something you love.",
    "Create a website about your coutry."
    ]